### ISSUE TITLE
Bug in "The Flash"

### ISSUE THREAD

**Issue by tatosjb** [rscafi/legtv-dl#4]
This app not works if name contains more of one word in name.

**Comment by ravanscafi** [comment]
Podemos falar em português por aqui, sem problemas.
Pode passar o nome do arquivo completo que ele não está achando?

**Comment by tatosjb** [comment]
the.flash.2014.121.hdtv-lol.mp4

**Comment by ravanscafi** [comment]
Estranho, testando pelo console, `the.flash.2014.121.hdtv-lol.mp4` está sendo identificado como `the flash s01e21` (o que está certo). E a busca também [retorna resultados](http://legendas.tv/util/carrega_legendas_busca/the%20flash%20s01e21).

 Que erro aparece no terminal?

**Comment by tatosjb** [comment]
https://drive.google.com/open?id=0B0795ISQ7W2TY182V19BTVlhdU0&authuser=0

**Comment by tatosjb** [comment]
https://drive.google.com/file/d/0B0795ISQ7W2TaDF2VG1WaUc2MlU/view?usp=sharing
